### ISSUE TITLE
Fast types?

### ISSUE THREAD

**Issue by ghost** [Keith-S-Thompson/how-to-c-response#10]
Hi, well done, thank you for this critique response.

Sorry for my ignorance, but why in bits like [[1](https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L61-L63)], [[2](https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L97)], [[3](https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L130)], or [[4](https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L145-L148)] only the "least" types are suggested, but not the "fast" [[5](https://en.cppreference.com/w/c/types/integer)] types as well?

\[1]: https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L61-L63
\[2]: https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L97
\[3]: https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L130
\[4]: https://github.com/Keith-S-Thompson/how-to-c-response/blame/fd3cdce3d8ada7366806f44de7b2c594816465b6/README.md#L145-L148
\[5]: https://en.cppreference.com/w/c/types/integer

**Comment by Keith-S-Thompson** [comment]
Good question. I'm not sure why I didn't mention the `[u]int_fastN_t` types. In some cases I referred specifically to a type that is "at least" some size, but in other cases either the `fast` or the `least` type would make sense.

I'll add a note at the end.

**Comment by Keith-S-Thompson** [comment]
Closed.

```
commit 8b672cb5514d4f1ed02350f14fc07b7831d0e9db
Author: Keith Thompson <Keith.S.Thompson@gmail.com>
Date:   2019-01-07 13:41:37 -0800

    Respond to issue #10
```
